name: Publish Website

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Hack to fix dubious ownership error: https://github.com/actions/checkout/issues/1048
      - name: Mark repository as safe
        run: git config --global --add safe.directory '*'

      - name: Build website
        run: make build-prod

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: out

  Publish:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Checkout Github pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Delete all files
        run: rm -rf ./*

      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: website

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          branch: gh-pages
          message: Update website