name: Publish Website
name: Publish Website

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find Go version
        run: awk '$1=="go"{print $2}' builder/go.mod | xargs -I {} echo "::set-output name=version::{}"
        id: go_mod

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go_mod.outputs.version }}

      - name: Build website
        run: make prod-build

      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: out

  Publish:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Checkout Github pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Delete all files
        run: rm -rf ./*

      - name: Download built artifacts
        uses: actions/download-artifact@v3
        with:
          name: website

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          branch: gh-pages
          message: Update website